apiVersion: v1
kind: Secret

metadata:
  name: payment-secret

type: Opaque

stringData:
  SPRING_MONGODB_URI: mongodb://admin:admin@payment-mongodb:27017/payment_db?authSource=admin
  JWK_SET_URI: http://keycloak:8080/realms/app-realm/protocol/openid-connect/certs