apiVersion: v1
kind: ConfigMap

metadata:
  name: gateway-config

data:
  JWK_SET_URI: "http://keycloak:8080/realms/app-realm/protocol/openid-connect/certs"
  GATEWAY_AUTH_SERVICE_URI: "http://auth-service:8082"
  GATEWAY_USER_SERVICE_URI: "http://user-service:8081"
  GATEWAY_ORDER_SERVICE_URI: "http://order-service:8083"
  GATEWAY_PAYMENT_SERVICE_URI: "http://payment-service:8084"