apiVersion: v1
kind: Secret
metadata:
  name: payment-mongodb-secret

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  MONGO_INITDB_DATABASE: "payment_db"