apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://user-postgres:5432/user_service"

  REDIS.HOST: "redis"
  REDIS_PORT: "6379"

  RESOURCE_SERVER_JWK_SET_URI: "http://keycloak:8080/realms/app-realm/protocol/openid-connect/certs"

  APP_USER: "appuser"