apiVersion: v1
kind: Secret

metadata:
  name: order-secret

type: Opaque

stringData:

  APP_USER: "appuser"

  APP_USER_PASSWORD: "1232312dwddsa"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://order-postgres:5432/order_service"