apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_DB: "postgres"
  KC_DB_URL_HOST: "keycloak-postgres"
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: "postgres"
  KC_DB_SCHEMA: "public"
  KC_HOSTNAME: "keycloak"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"