apiVersion: v1
kind: Secret
metadata:
  name: auth-secret

type: Opaque

stringData:
  SPRING_DATASOURCE_PASSWORD: 1232312dwddsa

  KEYCLOAK_ROOT_PASSWORD: admin
  KEYCLOAK_ROOT_SECRET: gUxWARNX4QK4bWtrC5JLoi520o1ixrQm

  KEYCLOAK_MANAGE_SECRET: gUxWARNX4QK4bWtrC5JLoi520o1ixrQm

  KEYCLOAK_AUTH_SECRET: gUxWARNX4QK4bWtrC5JLoi520o1ixrQm

  KC_ADMIN_PASSWORD: admin
  KC_DB_PASSWORD: postgres

  DB_PASSWORD: admin
  APP_USER_PASSWORD: 1232312dwddsa